# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [23,23], mode: outbond }
                background: { size: [24,24], position: center, color: '#000000'}

        miniature:
            quality: 85
            filters:
                thumbnail: 
                    size: [40,40]
                    mode: outbound

        miniature_hi:
            quality: 85
            filters:
                thumbnail: 
                    size: [60,60]
                    mode: outbound

        miniature_small:
            quality: 85
            filters:
                thumbnail: 
                    size: [25,25]
                    mode: outbound
